# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [4]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

height =np.array([69, 70, 71, 72, 73, 74, 75])
weight = np.array([110, 120, 130, 140, 150, 160, 170])
bmi = np.round((weight / (height**2) * 730),decimals = 2)
bmi 

array([16.87, 17.88, 18.83, 19.71, 20.55, 21.33, 22.06])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [15]:
import numpy as np 
def makeRandoMatrix(minValue, maxValue, shape): 
    """
    make a random matrix! 
    minValue = int
    maxValue = int 
    shape = (int, int)"""
    matrix = np.round((np.random.uniform(minValue,maxValue, shape)), decimals = 2) 
    return matrix 

print(makeRandoMatrix(0,10,(3,3)))


[[6.13 6.26 8.93]
 [9.18 2.74 5.17]
 [7.66 7.12 9.65]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [16]:
import csv
import numpy as np

def open_csv(filename, d=','):
    # define an empty list to store data
    data = []
    
    # use the 'with' keyword to load from csv and store into data
    with open(filename, encoding='utf-8-sig') as mData:
        # use reader method in csv package to create python list
        info = csv.reader(mData, delimiter = d)
        print(info)
        
        # loop over info and append to data
        for row in info:
            data.append(row)
        
    # no need to close file, using with statement closes automatically
    return data

csv_data = open_csv('../Desktop/Coding Temple Assignments/boston_marathon2017_edited.csv')


In [27]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d = ','):
    data = np.genfromtxt(filename,delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24),invalid_raise=False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('../Downloads/redsox_2017_hitting.txt')
bs2018 = load_data('../Downloads/redsox_2018_hitting.txt')

avgslg2017 = sum(bs2017["SLG"])/len(bs2017["SLG"])
avgslg2018 = sum(bs2018["SLG"])/len(bs2018["SLG"])

avg_slg = (avgslg2018,avgslg2017)

print(f"This is the SLG avg for 2017: {avgslg2017}")
print(f"This is the SLG avg for 2018: {avgslg2018}")

print(f'The SLG avg was {(max(avg_slg) - min(avg_slg))} higher in 2017.')



This is the SLG avg for 2017: 0.39334782374941785
This is the SLG avg for 2018: 0.38750000335276125
The SLG avg was 0.0058478203966566 higher in 2017
